version: "3"

services:
  ruby:
    build:
      dockerfile: Dockerfile_ruby
      context: .
    image: exercism-ruby
    volumes:
      - ./ruby:/home/exercism/ruby
      - ./.config/exercism:/home/exercism/.config/exercism
  bash:
    build:
      dockerfile: Dockerfile_bash
      context: .
    image: exercism-bash
    volumes:
      - ./bash:/home/exercism/bash
      - ./.config/exercism:/home/exercism/.config/exercism
